# Generated by Django 4.0.2 on 2022-05-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='tag',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
