# Generated by Django 4.0.2 on 2022-05-05 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meme', '0002_meme_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
