# Generated by Django 4.0.2 on 2022-05-05 05:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0003_meme_favorites'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='meme',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
