# Generated by Django 4.0.2 on 2022-05-14 03:15

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('meme', '0004_alter_meme_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='meme',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='meme',
            name='tag',
        ),
        migrations.AddField(
            model_name='meme',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
