# Generated by Django 4.0.2 on 2022-03-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeSite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meme',
        ),
    ]
